# Generated by Django 2.1.2 on 2018-12-03 10:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0002_auto_20181203_1506'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='aspnetroles',
            options={'managed': True, 'verbose_name_plural': 'Aspnetroles'},
        ),
        migrations.AlterModelOptions(
            name='aspnetusers',
            options={'managed': True, 'verbose_name_plural': 'Aspnetusers'},
        ),
        migrations.AlterModelOptions(
            name='attendance',
            options={'managed': True, 'verbose_name_plural': 'Attendance'},
        ),
        migrations.AlterModelOptions(
            name='company',
            options={'managed': True, 'verbose_name_plural': 'Company'},
        ),
        migrations.AlterModelOptions(
            name='document',
            options={'managed': True, 'verbose_name_plural': 'Document'},
        ),
        migrations.AlterModelOptions(
            name='leaditems',
            options={'managed': True, 'verbose_name_plural': 'Leaditems'},
        ),
        migrations.AlterModelOptions(
            name='leads',
            options={'managed': True, 'verbose_name_plural': 'Leads'},
        ),
        migrations.AlterModelOptions(
            name='project',
            options={'managed': True, 'verbose_name_plural': 'Project'},
        ),
        migrations.AlterField(
            model_name='document',
            name='projectid',
            field=models.IntegerField(),
        ),
    ]
