# Generated by Django 2.1.2 on 2018-12-06 07:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0004_auto_20181206_1206'),
    ]

    operations = [
        migrations.RenameField(
            model_name='leads',
            old_name='status',
            new_name='statusid',
        ),
    ]
