# Generated by Django 2.1.2 on 2018-12-08 02:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0005_auto_20181206_1244'),
    ]

    operations = [
        migrations.CreateModel(
            name='Profilepics',
            fields=[
                ('username', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('pics', models.ImageField(upload_to='')),
            ],
            options={
                'verbose_name_plural': 'profilepics',
                'db_table': 'profilepics',
                'managed': True,
            },
        ),
    ]
